# Generated by Django 4.2.2 on 2023-10-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0003_silverpackage_platinumpackage_goldpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpackage',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
