# Generated by Django 4.2.2 on 2023-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0004_goldpackage_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='platinumpackage',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='silverpackage',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
