# Generated by Django 4.2.2 on 2023-11-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0007_goldpackage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldpackage',
            name='status',
        ),
    ]
