# Generated by Django 4.2.2 on 2023-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0009_customisepackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customisepackage',
            old_name='total_amount',
            new_name='billing_info',
        ),
        migrations.RenameField(
            model_name='customisepackage',
            old_name='location_to_shoot',
            new_name='location',
        ),
    ]
