# Generated by Django 4.2.2 on 2023-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0010_rename_total_amount_customisepackage_billing_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisepackage',
            name='honeymoon_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
