# Generated by Django 4.2.2 on 2023-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0011_alter_customisepackage_honeymoon_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customisepackage',
            name='travelling',
            field=models.CharField(default='', max_length=255),
        ),
    ]
