# Generated by Django 4.2.2 on 2023-11-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0013_alter_customisepackage_travelling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customisepackage',
            name='travelling',
        ),
    ]
