# Generated by Django 4.2.2 on 2023-11-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0015_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
