# Generated by Django 4.2.2 on 2023-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0017_vendorprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
