# Generated by Django 4.2.2 on 2023-11-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0018_vendorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='verification_code',
        ),
    ]
