# Generated by Django 4.2.2 on 2023-11-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0019_remove_vendorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
