# Generated by Django 4.2.2 on 2023-11-19 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0023_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('destination_selected', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmBookingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('confirm_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapp.confirmbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
