# Generated by Django 4.2.2 on 2023-11-19 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0024_confirmbooking_confirmbookingapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
                ('destination', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='confirmbookingapplication',
            name='confirm_booking',
        ),
        migrations.RemoveField(
            model_name='confirmbookingapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfirmBooking',
        ),
        migrations.DeleteModel(
            name='ConfirmBookingApplication',
        ),
    ]
