# Generated by Django 4.2.2 on 2023-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0026_rename_destination_booking_destination_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpackage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
