# Generated by Django 4.2.2 on 2023-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0027_goldpackage_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisepackage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platinumpackage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='silverpackage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
