# Generated by Django 4.2.2 on 2024-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0031_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpackage',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='gold_package_applicants', to='weddingapp.vendorprofile'),
        ),
    ]
