# Generated by Django 4.2.2 on 2024-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0032_goldpackage_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisepackage',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='customise_package_applicants', to='weddingapp.vendorprofile'),
        ),
        migrations.AddField(
            model_name='platinumpackage',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='platinum_package_applicants', to='weddingapp.vendorprofile'),
        ),
        migrations.AddField(
            model_name='silverpackage',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='silver_package_applicants', to='weddingapp.vendorprofile'),
        ),
    ]
