# file created: 2024-02-12 05:03:52.093337

# this files has been generated by CandyTranslate.com  Please do not change manually
# author: Next Level Sense

# Available functions:
#    render - replacement for django render function
#    path - replacement for django path function. please use with * when replacing in urls.py
#    supported_languages - list that contains all available languages for this site
# Functions to be used in django templates:
#    languageReferences - create 'alternate' language references for SEO.
#        put it inside of the <head> section of the page in format {{languageReferences|safe}}
#    lang - current language. Used mostly in <html lang="{{lang}}">
#    languageMenu - adding language selection for your page. Format: {{languageMenu|safe}}
#    <<link variables>> - create linking to correct language link. 
#    usage:
#    for translated pages change {% url "my_page" %}
#    to name without quotes:     {% url my_page %}


supported_languages = ['en', 'bn', 'fr', 'hi', 'es', 'ta', 'ur']

def translation_dictionary(lang):
    if lang == 'en': return {
        'cancel_Bcancel':'''Your booking has been cancelled''',
        'cancel_cmail':'''Cancellation Mail will be sended soon''',
        'cancel_done':'''DONE''',
        'changepass_current':'''Current Password:''',
        'changepass_new':'''New Password:''',
        'confirm_Bconfirm':'''Your booking has been confirmed''',
        'confirm_conmail':'''Confirmation Mail will be sended soon''',
        'confirm_condone':'''DONE''',
        'index_happy':'''HAPPY WEDDING''',
        'index_HOME':'''Home''',
        'index_ABOUT':'''About''',
        'index_DEST':'''Destination''',
        'index_PRICE':'''Pricing''',
        'index_SIGN':'''Signup''',
        'index_HEY':'''Hey I am Vendor''',
        'index_TEA':'''Team''',
        'index_LOG':'''LogIn''',
        'index_CONT':'''Contact''',
        'index_WEL':'''Welcome''',
        'index_DESC':'''We are team of talented organisers to make your MOMENTS''',
        'index_START':'''Get Started''',
        'index_Aboutsite':'''Our HAPPY WEDDING is  a place to share the love story of the couple, their journey to choosing a destination wedding, and their excitement about the upcoming celebration. It provides a personal touch, giving guests insight into the couple's relationship and the reasons behind their choice of a destination for their special day. We also include details about the destination's significance and what guests can look forward to during the wedding festivities. Overall, it sets the tone for the wedding experience and invites guests to be part of the couple's unique journey.''',
        'index_ques':'''What to Expect''',
        'index_detail':'''Get ready for a celebration filled with love, laughter, and unforgettable moments. From beachside ceremonies to exploring local cuisine and culture, we've planned an unforgettable experience for our wedding guests. Explore our website to find details on travel arrangements, accommodations, and activities during our special weekend.''',
        'index_Destinations':'''DESTINATIONS''',
        'index_delhi':'''DELHI''',
        'index_delhidesc':'''The Capital of country, Is the capital for ethnic and gorgeous wedding''',
        'index_rajasthan':'''RAJASTHAN''',
        'index_rajdesc':'''The Pink City of INDIA, Will make your wedding Colorfull''',
        'index_kerala':'''KERALA''',
        'index_keraladesc':'''God's Own Country of INDIA, where HEAVEN falls''',
        'index_swiz':'''SWITZERLAND''',
        'index_swizdesc':'''If you have a wish to have PURE and PEACE wedding''',
        'index_luxe':'''LUXEMBURG''',
        'index_luxedesc':'''The destination where you can have MOMENTS''',
        'index_paris':'''PARIS''',
        'index_parisdesc':'''The DESTINATION for RICH and MEMORABLE wedding''',
        'index_price1':'''Pricing''',
        'index_price2':'''Pricing''',
        'index_desired':'''CHOOSE  THE DESIRED PACKAGE''',
        'index_customise':'''CUSTOMISE''',
        'index_customise1':'''customise''',
        'index_needs':'''Your needs''',
        'index_addson':'''With ADDS-on advnatage''',
        'index_Customise2':'''Customise''',
        'index_GOLD':'''GOLD''',
        'index_cusine':'''INDIAN CUISINE''',
        'index_indian':'''INDIAN DESTINATION ONLY''',
        'index_MUSIC':'''MUSIC''',
        'index_PHOTOGRAPY':'''PHOTOGRAPY''',
        'index_ACCODOMATIONS':'''ACCODOMATIONS''',
        'index_DECORATORATION1':'''DECORATORATION''',
        'index_guest':'''100 GUESTS''',
        'index_buynow':'''Buy Now''',
        'index_SILVER':'''SILVER''',
        'index_cont':'''INDIAN OR CONTINENTAL CUISINE''',
        'index_honey':'''INDIAN DESTINATION WITH FREE HONEYMOON PACKAGE''',
        'index_ facility':'''TRAVELLING FACILITY''',
        'index_class':'''S CLASS-ACCODOMATIONS''',
        'index_dj ':'''MUSIC AND DJ NIGHT''',
        'index_after':'''AFTER MARRIAGE SHOOTING''',
        'index_PHOTO':'''PHOTOGRAPY''',
        'index_DECORATORATION2':'''DECORATORATION''',
        'index_guests1':'''100-150 GUESTS''',
        'index_PLATINUM':'''PLATINUM''',
        'index_withb':'''INDIAN AND CONTINENTAL CUISINE WITH BEVERAGES''',
        'index_honeyp':'''INDIAN AND INTERNATIONAL DESTINATION WITH FREE HONEYMOON PACKAGE''',
        'index_facilitybus':'''AIRBUS  FACILITY''',
        'index_class':'''5 STAR CLASS-ACCODOMATIONS''',
        'index_djnight':'''MUSIC , DJ NIGHT AND LIVE CONCERT''',
        'index_projection':'''AFTER MARRIAGE SHOOTING WITH PROJECTOR DISPLAY''',
        'index_ photograpy':'''DESTIANTION PHOTOGRAPY''',
        'index_ decorator':'''INTERNATIONAL DECORATORATION''',
        'index_GUESTS':'''100GUESTS''',
        'index_Team2':'''Team''',
        'index_your ':'''OUR TEAM MEMBERS TO DESIGN YOUR HAPPINESS''',
        'index_king':'''ZACK KING''',
        'index_chief':'''Chief Executive Officer''',
        'index_our':'''Crafting Dreams, Making Memories: Your Destination, Our Expertise."''',
        'index_patel':'''DRISHTI PATEL''',
        'index_productmanager':'''Product Manager''',
        'index_unforgettable ':'''Turning Dreams into Unforgettable Destinations''',
        'index_lucy':'''LUCIFIER KING''',
        'index_CTO':'''CTO''',
        'index_memories':'''"Crafting Dreams, Creating Memories: Your Perfect Destination Wedding."''',
        'index_Contact2':'''Contact''',
        'index_whene':'''Contact Us whenever You Want''',
        'index_ouraddress':'''Our Address''',
        'index_address':'''A108 Adam Street,New Delhi,535022''',
        'index_emailus':'''Email Us''',
        'index_com':'''happywedding@gmail.com''',
        'index_callus':'''Call Us''',
        'index_Copyright':'''Copyright ''',
        'index_all':'''All Rights Reserved''',
        'index_by':'''Designed by''',
        'index_hawed':'''Why a HAPPY WEDDING ?''',
        'index_decision':'''For us, the decision to have a destination wedding was an easy one. It's a reflection of our love for travel and our desire to create lasting memories with our closest friends and family. We couldn't imagine a more beautiful place to exchange our vows.''',
        'signup_cust':'''CUSTOMER SIGNUP''',
        'signup_first':'''First Name:''',
        'signup_last':'''Last Name:''',
        'signup_ema':'''Email:''',
        'signup_uname':'''Username''',
        'signup_pass':'''Password''',
        'signup_cpass':'''Confirm Password:''',
        'signup_up':'''Sign Up''',
        }
    if lang == 'bn': return {
        'cancel_Bcancel':'''আপনার বুকিং বাতিল করা হয়েছে''',
        'cancel_cmail':'''বাতিলকরণ মেল শীঘ্রই প্রেরণ করা হবে''',
        'cancel_done':'''সম্পন্ন''',
        'changepass_current':'''বর্তমান পাসওয়ার্ড:''',
        'changepass_new':'''নতুন পাসওয়ার্ড:''',
        'confirm_Bconfirm':'''আপনার বুকিং নিশ্চিত করা হয়েছে''',
        'confirm_conmail':'''নিশ্চিতকরণ মেল শীঘ্রই প্রেরণ করা হবে''',
        'confirm_condone':'''সম্পন্ন''',
        'index_happy':'''শুভ বিবাহ''',
        'index_HOME':'''বাড়ি''',
        'index_ABOUT':'''সম্পর্কিত''',
        'index_DEST':'''গন্তব্য''',
        'index_PRICE':'''মূল্য নির্ধারণ''',
        'index_SIGN':'''নিবন্ধন করুন''',
        'index_HEY':'''আরে আমি বিক্রেতা''',
        'index_TEA':'''টীম''',
        'index_LOG':'''প্রবেশ করুন''',
        'index_CONT':'''যোগাযোগ''',
        'index_WEL':'''স্বাগত''',
        'index_DESC':'''আমরা আপনার মুহুর্তগুলি তৈরি করতে প্রতিভাবান সংগঠকদের দল''',
        'index_START':'''এবার শুরু করা যাক''',
        'index_Aboutsite':'''আমাদের সুখী বিবাহ এই দম্পতির প্রেমের গল্প, গন্তব্য বিবাহ বেছে নেওয়ার যাত্রা এবং আসন্ন উদযাপন সম্পর্কে তাদের উত্তেজনা ভাগ করে নেওয়ার জায়গা। এটি একটি ব্যক্তিগত স্পর্শ সরবরাহ করে, অতিথিদের দম্পতির সম্পর্ক এবং তাদের বিশেষ দিনের জন্য কোনও গন্তব্য পছন্দের পিছনে কারণগুলি অন্তর্দৃষ্টি দেয়। আমরা গন্তব্যটির তাত্পর্য এবং বিবাহের উত্সব চলাকালীন অতিথিরা কী অপেক্ষায় থাকতে পারে সে সম্পর্কে বিশদও অন্তর্ভুক্ত করি। সামগ্রিকভাবে, এটি বিবাহের অভিজ্ঞতার জন্য সুরটি সেট করে এবং অতিথিদের দম্পতির অনন্য যাত্রার অংশ হতে আমন্ত্রণ জানায়।''',
        'index_ques':'''কি আশা করছ''',
        'index_detail':'''প্রেম, হাসি এবং অবিস্মরণীয় মুহুর্তে ভরা উদযাপনের জন্য প্রস্তুত হন। সৈকত অনুষ্ঠান থেকে শুরু করে স্থানীয় খাবার এবং সংস্কৃতি অন্বেষণ পর্যন্ত আমরা আমাদের বিবাহের অতিথিদের জন্য একটি অবিস্মরণীয় অভিজ্ঞতা পরিকল্পনা করেছি। আমাদের বিশেষ উইকএন্ডে ভ্রমণের ব্যবস্থা, থাকার ব্যবস্থা এবং ক্রিয়াকলাপগুলির বিশদ জানতে আমাদের ওয়েবসাইটটি অন্বেষণ করুন।''',
        'index_Destinations':'''গন্তব্য''',
        'index_delhi':'''দিল্লি''',
        'index_delhidesc':'''দেশের রাজধানী, জাতিগত এবং চমত্কার বিবাহের রাজধানী''',
        'index_rajasthan':'''রাজস্থান''',
        'index_rajdesc':'''ভারতের গোলাপী শহর, আপনার বিবাহকে রঙিন করে তুলবে''',
        'index_kerala':'''কেরালা''',
        'index_keraladesc':'''Of শ্বরের নিজস্ব দেশ, যেখানে স্বর্গ পড়ে যায়''',
        'index_swiz':'''সুইজারল্যান্ড''',
        'index_swizdesc':'''আপনার যদি খাঁটি এবং শান্তি বিবাহের ইচ্ছা থাকে''',
        'index_luxe':'''লাক্সেমবার্গ''',
        'index_luxedesc':'''গন্তব্য যেখানে আপনি মুহুর্তগুলি থাকতে পারেন''',
        'index_paris':'''প্যারিস''',
        'index_parisdesc':'''সমৃদ্ধ এবং স্মরণীয় বিবাহের গন্তব্য''',
        'index_price1':'''মূল্য নির্ধারণ''',
        'index_price2':'''মূল্য নির্ধারণ''',
        'index_desired':'''পছন্দসই প্যাকেজটি চয়ন করুন''',
        'index_customise':'''কাস্টমাইজ''',
        'index_customise1':'''কাস্টমাইজ''',
        'index_needs':'''আপনার চাহিদা''',
        'index_addson':'''অ্যাডস-অন অ্যাডন্যাটেজ সহ''',
        'index_Customise2':'''কাস্টমাইজ''',
        'index_GOLD':'''স্বর্ণ''',
        'index_cusine':'''ভারতীয় খাবার''',
        'index_indian':'''কেবল ভারতীয় গন্তব্য''',
        'index_MUSIC':'''সংগীত''',
        'index_PHOTOGRAPY':'''ফটোগ্রাফাপি''',
        'index_ACCODOMATIONS':'''অভিযান''',
        'index_DECORATORATION1':'''সাজসজ্জা''',
        'index_guest':'''100 অতিথি''',
        'index_buynow':'''এখন কেন''',
        'index_SILVER':'''রৌপ্য''',
        'index_cont':'''ভারতীয় বা মহাদেশীয় খাবার''',
        'index_honey':'''বিনামূল্যে হানিমুন প্যাকেজ সহ ভারতীয় গন্তব্য''',
        'index_ facility':'''ভ্রমণ সুবিধা''',
        'index_class':'''এস ক্লাস-অ্যাকোডোমেশনস''',
        'index_dj ':'''সংগীত এবং ডিজে নাইট''',
        'index_after':'''বিয়ের শুটিংয়ের পরে''',
        'index_PHOTO':'''ফটোগ্রাফাপি''',
        'index_DECORATORATION2':'''সাজসজ্জা''',
        'index_guests1':'''100-150 অতিথি''',
        'index_PLATINUM':'''প্ল্যাটিনাম''',
        'index_withb':'''পানীয় সহ ভারতীয় এবং মহাদেশীয় খাবার''',
        'index_honeyp':'''বিনামূল্যে হানিমুন প্যাকেজ সহ ভারতীয় এবং আন্তর্জাতিক গন্তব্য''',
        'index_facilitybus':'''এয়ারবাস সুবিধা''',
        'index_class':'''5 তারকা শ্রেণি-অ্যাকোডোমেশনস''',
        'index_djnight':'''সংগীত, ডিজে নাইট এবং লাইভ কনসার্ট''',
        'index_projection':'''প্রজেক্টর প্রদর্শনের সাথে বিবাহের শুটিংয়ের পরে''',
        'index_ photograpy':'''ডেসটিয়েশন ফটোগ্রাফাপি''',
        'index_ decorator':'''আন্তর্জাতিক সাজসজ্জা''',
        'index_GUESTS':'''100 গেস্টস''',
        'index_Team2':'''টীম''',
        'index_your ':'''আমাদের দলের সদস্যরা আপনার সুখ ডিজাইন করতে''',
        'index_king':'''জ্যাক কিং''',
        'index_chief':'''প্রধান নির্বাহী কর্মকর্তা''',
        'index_our':'''স্বপ্ন তৈরি করা, স্মৃতি তৈরি করা: আপনার গন্তব্য, আমাদের দক্ষতা। "''',
        'index_patel':'''দ্রীষ্ঠী প্যাটেল''',
        'index_productmanager':'''পণ্য ব্যবস্থাপক''',
        'index_unforgettable ':'''স্বপ্নকে অবিস্মরণীয় গন্তব্যে পরিণত করা''',
        'index_lucy':'''লুসিফায়ার কিং''',
        'index_CTO':'''সিটিও''',
        'index_memories':'''"স্বপ্ন তৈরি করা, স্মৃতি তৈরি করা: আপনার নিখুঁত গন্তব্য বিবাহ" "''',
        'index_Contact2':'''যোগাযোগ''',
        'index_whene':'''আপনি যখনই চান আমাদের সাথে যোগাযোগ করুন''',
        'index_ouraddress':'''আমাদের ঠিকানা''',
        'index_address':'''এ 108 অ্যাডাম স্ট্রিট, নয়াদিল্লি, 535022''',
        'index_emailus':'''আমাদেরকে ইমেইল করুন''',
        'index_com':'''হ্যাপিওয়েডিং@gmail.com''',
        'index_callus':'''আমাদের কল''',
        'index_Copyright':'''কপিরাইট''',
        'index_all':'''সমস্ত অধিকার সংরক্ষিত''',
        'index_by':'''ডিজাইন করেছেন''',
        'index_hawed':'''কেন সুখী বিয়ে?''',
        'index_decision':'''আমাদের জন্য ডেস্টিনেশন ওয়েডিংয়ের সিদ্ধান্তটা সহজ ছিল। এটি ভ্রমণের প্রতি আমাদের ভালবাসা এবং আমাদের নিকটতম বন্ধুবান্ধব এবং পরিবারের সাথে স্থায়ী স্মৃতি তৈরি করার আমাদের আকাঙ্ক্ষার প্রতিফলন। আমরা আমাদের প্রতিজ্ঞা বিনিময় করার জন্য এর চেয়ে সুন্দর জায়গা কল্পনা করতে পারি না।''',
        'signup_cust':'''গ্রাহক সাইনআপ''',
        'signup_first':'''নামের প্রথম অংশ:''',
        'signup_last':'''নামের শেষাংশ:''',
        'signup_ema':'''ইমেল:''',
        'signup_uname':'''ব্যবহারকারীর নাম''',
        'signup_pass':'''পাসওয়ার্ড''',
        'signup_cpass':'''পাসওয়ার্ড নিশ্চিত করুন:''',
        'signup_up':'''নিবন্ধন করুন''',
        }
    if lang == 'fr': return {
        'cancel_Bcancel':'''Votre réservation a été annulée''',
        'cancel_cmail':'''Le courrier d'annulation sera bientôt envoyé''',
        'cancel_done':'''FAIT''',
        'changepass_current':'''Mot de passe actuel:''',
        'changepass_new':'''Nouveau mot de passe:''',
        'confirm_Bconfirm':'''Votre réservation a été confirmée''',
        'confirm_conmail':'''Le courrier de confirmation sera envoyé bientôt''',
        'confirm_condone':'''FAIT''',
        'index_happy':'''Joyeux mariage''',
        'index_HOME':'''Maison''',
        'index_ABOUT':'''À propos''',
        'index_DEST':'''Destination''',
        'index_PRICE':'''Prix''',
        'index_SIGN':'''S'inscrire''',
        'index_HEY':'''Hey je suis vendeur''',
        'index_TEA':'''Équipe''',
        'index_LOG':'''Se connecter''',
        'index_CONT':'''Contact''',
        'index_WEL':'''Accueillir''',
        'index_DESC':'''Nous sommes une équipe d'organisateurs talentueux pour faire vos moments''',
        'index_START':'''Commencer''',
        'index_Aboutsite':'''Notre heureux mariage est un endroit pour partager l'histoire d'amour du couple, leur voyage vers le choix d'un mariage à destination et leur excitation à propos de la prochaine célébration. Il fournit une touche personnelle, donnant aux clients un aperçu de la relation du couple et des raisons de leur choix de destination pour leur journée spéciale. Nous incluons également des détails sur la signification de la destination et ce que les clients peuvent attendre avec impatience pendant les festivités de mariage. Dans l'ensemble, cela donne le ton à l'expérience de mariage et invite les invités à faire partie du voyage unique du couple.''',
        'index_ques':'''À quoi s'attendre''',
        'index_detail':'''Préparez-vous pour une célébration remplie d'amour, de rires et de moments inoubliables. Des cérémonies en bord de mer à l'exploration de la cuisine et de la culture locales, nous avons prévu une expérience inoubliable pour nos invités de mariage. Explorez notre site Web pour trouver des détails sur les dispositions de voyage, l'hébergement et les activités pendant notre week-end spécial.''',
        'index_Destinations':'''Destination''',
        'index_delhi':'''Delhi''',
        'index_delhidesc':'''La capitale du pays, est la capitale du mariage ethnique et magnifique''',
        'index_rajasthan':'''Rajasthan''',
        'index_rajdesc':'''La ville rose de l'Inde rendra votre mariage coloré''',
        'index_kerala':'''Kerala''',
        'index_keraladesc':'''Le propre pays de Dieu de l'Inde, où le ciel tombe''',
        'index_swiz':'''SUISSE''',
        'index_swizdesc':'''Si vous souhaitez avoir un mariage pur et de paix''',
        'index_luxe':'''Luxembourg''',
        'index_luxedesc':'''La destination où vous pouvez avoir des moments''',
        'index_paris':'''PARIS''',
        'index_parisdesc':'''La destination pour un mariage riche et mémorable''',
        'index_price1':'''Prix''',
        'index_price2':'''Prix''',
        'index_desired':'''Choisissez le package souhaité''',
        'index_customise':'''PERSONNALISER''',
        'index_customise1':'''Personnaliser''',
        'index_needs':'''Vos besoins''',
        'index_addson':'''Avec addS-on advnatage''',
        'index_Customise2':'''Personnaliser''',
        'index_GOLD':'''OR''',
        'index_cusine':'''CUISINE INDIENNE''',
        'index_indian':'''Destination indienne uniquement''',
        'index_MUSIC':'''MUSIQUE''',
        'index_PHOTOGRAPY':'''Photograpie''',
        'index_ACCODOMATIONS':'''Accrodomations''',
        'index_DECORATORATION1':'''Décorateur''',
        'index_guest':'''100 invités''',
        'index_buynow':'''Acheter maintenant''',
        'index_SILVER':'''ARGENT''',
        'index_cont':'''Cuisine indienne ou continentale''',
        'index_honey':'''Destination indienne avec forfait de lune de miel gratuit''',
        'index_ facility':'''Installation de voyage''',
        'index_class':'''S de la classe''',
        'index_dj ':'''Musique et nuit de DJ''',
        'index_after':'''Après le tir du mariage''',
        'index_PHOTO':'''Photograpie''',
        'index_DECORATORATION2':'''Décorateur''',
        'index_guests1':'''100-150 invités''',
        'index_PLATINUM':'''PLATINE''',
        'index_withb':'''Cuisine indienne et continentale avec des boissons''',
        'index_honeyp':'''Destination indienne et internationale avec forfait de lune de miel gratuit''',
        'index_facilitybus':'''Airbus Facility''',
        'index_class':'''5 étoiles de classe''',
        'index_djnight':'''Musique, DJ Night and Live Concert''',
        'index_projection':'''Après le tournage du mariage avec l'affichage du projecteur''',
        'index_ photograpy':'''Photograpie de la Destiantion''',
        'index_ decorator':'''Décorator international''',
        'index_GUESTS':'''100gueurs''',
        'index_Team2':'''Équipe''',
        'index_your ':'''Les membres de notre équipe pour concevoir votre bonheur''',
        'index_king':'''Zack King''',
        'index_chief':'''Directeur général''',
        'index_our':'''Créer des rêves, faire des souvenirs: votre destination, notre expertise. "''',
        'index_patel':'''Drishti Patel''',
        'index_productmanager':'''Chef de produit''',
        'index_unforgettable ':'''Transformer les rêves en destinations inoubliables''',
        'index_lucy':'''Roi lucifier''',
        'index_CTO':'''CTO''',
        'index_memories':'''"Créer des rêves, créer des souvenirs: votre mariage parfait à destination."''',
        'index_Contact2':'''Contact''',
        'index_whene':'''Contactez-nous quand vous le souhaitez''',
        'index_ouraddress':'''Notre adresse''',
        'index_address':'''A108 Adam Street, New Delhi, 535022''',
        'index_emailus':'''Envoyez-nous un email''',
        'index_com':'''happywedding@gmail.com''',
        'index_callus':'''Nous appeler''',
        'index_Copyright':'''droits d'auteur''',
        'index_all':'''Tous droits réservés''',
        'index_by':'''Conçu par''',
        'index_hawed':'''Pourquoi un HAPPY WEDDING ?''',
        'index_decision':'''Pour nous, la décision d’organiser un mariage à destination a été facile à prendre. C’est le reflet de notre amour pour les voyages et de notre désir de créer des souvenirs inoubliables avec nos amis les plus proches et notre famille. Nous ne pouvions pas imaginer un plus bel endroit pour échanger nos vœux.''',
        'signup_cust':'''Inscription du client''',
        'signup_first':'''Prénom:''',
        'signup_last':'''Nom de famille:''',
        'signup_ema':'''E-mail:''',
        'signup_uname':'''Nom d'utilisateur''',
        'signup_pass':'''Mot de passe''',
        'signup_cpass':'''Confirmez le mot de passe:''',
        'signup_up':'''S'inscrire''',
        }
    if lang == 'hi': return {
        'cancel_Bcancel':'''आपकी बुकिंग रद्द कर दी गई है''',
        'cancel_cmail':'''रद्दीकरण मेल जल्द ही भेजा जाएगा''',
        'cancel_done':'''हो गया''',
        'changepass_current':'''वर्तमान पासवर्ड:''',
        'changepass_new':'''नया पासवर्ड:''',
        'confirm_Bconfirm':'''आपकी बुकिंग की पुष्टि की गई है''',
        'confirm_conmail':'''पुष्टिकरण मेल जल्द ही भेजा जाएगा''',
        'confirm_condone':'''हो गया''',
        'index_happy':'''शादी की शुभकामनाएं''',
        'index_HOME':'''घर''',
        'index_ABOUT':'''के बारे में''',
        'index_DEST':'''गंतव्य''',
        'index_PRICE':'''मूल्य निर्धारण''',
        'index_SIGN':'''साइन अप करें''',
        'index_HEY':'''अरे मैं विक्रेता हूं''',
        'index_TEA':'''टीम''',
        'index_LOG':'''लॉग इन करें''',
        'index_CONT':'''संपर्क''',
        'index_WEL':'''स्वागत''',
        'index_DESC':'''हम अपने क्षण बनाने के लिए प्रतिभाशाली आयोजकों की टीम हैं''',
        'index_START':'''शुरू हो जाओ''',
        'index_Aboutsite':'''हमारी हैप्पी वेडिंग युगल की प्रेम कहानी, गंतव्य शादी को चुनने की उनकी यात्रा और आगामी उत्सव के बारे में उनकी उत्तेजना को साझा करने के लिए एक जगह है। यह एक व्यक्तिगत स्पर्श प्रदान करता है, जो मेहमानों को युगल के रिश्ते में अंतर्दृष्टि देता है और उनके विशेष दिन के लिए एक गंतव्य की पसंद के पीछे के कारण। हम गंतव्य के महत्व के बारे में भी विवरण शामिल करते हैं और मेहमान शादी के उत्सव के दौरान आगे क्या देख सकते हैं। कुल मिलाकर, यह शादी के अनुभव के लिए टोन सेट करता है और मेहमानों को युगल की अनूठी यात्रा का हिस्सा बनने के लिए आमंत्रित करता है।''',
        'index_ques':'''क्या उम्मीद करें''',
        'index_detail':'''प्यार, हँसी और अविस्मरणीय क्षणों से भरे उत्सव के लिए तैयार हो जाओ। समुद्र तट समारोहों से लेकर स्थानीय व्यंजनों और संस्कृति की खोज करने के लिए, हमने अपने शादी के मेहमानों के लिए एक अविस्मरणीय अनुभव की योजना बनाई है। हमारे विशेष सप्ताहांत के दौरान यात्रा व्यवस्था, आवास और गतिविधियों के बारे में विवरण खोजने के लिए हमारी वेबसाइट का अन्वेषण करें।''',
        'index_Destinations':'''गंतव्यों''',
        'index_delhi':'''दिल्ली''',
        'index_delhidesc':'''देश की राजधानी, जातीय और भव्य शादी की राजधानी है''',
        'index_rajasthan':'''राजस्थान RAJASTHAN''',
        'index_rajdesc':'''भारत का गुलाबी शहर, आपकी शादी को रंगीन बना देगा''',
        'index_kerala':'''केरल''',
        'index_keraladesc':'''भारत का अपना देश, जहां स्वर्ग गिरता है''',
        'index_swiz':'''स्विट्ज़रलैंड''',
        'index_swizdesc':'''यदि आपके पास शुद्ध और शांति शादी की इच्छा है''',
        'index_luxe':'''लक्समबर्ग''',
        'index_luxedesc':'''वह गंतव्य जहां आपके पास क्षण हो सकते हैं''',
        'index_paris':'''पेरिस''',
        'index_parisdesc':'''अमीर और यादगार शादी के लिए गंतव्य''',
        'index_price1':'''मूल्य निर्धारण''',
        'index_price2':'''मूल्य निर्धारण''',
        'index_desired':'''वांछित पैकेज चुनें''',
        'index_customise':'''अनुकूलित करें''',
        'index_customise1':'''अनुकूलित करें''',
        'index_needs':'''आपकी ज़रूरतें''',
        'index_addson':'''Adds-on advnatage के साथ''',
        'index_Customise2':'''अनुकूलित करें''',
        'index_GOLD':'''सोना''',
        'index_cusine':'''भारतीय क्विजिन''',
        'index_indian':'''केवल भारतीय गंतव्य''',
        'index_MUSIC':'''संगीत''',
        'index_PHOTOGRAPY':'''फोटोग्रैपी''',
        'index_ACCODOMATIONS':'''उपकला''',
        'index_DECORATORATION1':'''सजावट''',
        'index_guest':'''100 मेहमान''',
        'index_buynow':'''अभी खरीदें''',
        'index_SILVER':'''चाँदी''',
        'index_cont':'''भारतीय या महाद्वीपीय भोजन''',
        'index_honey':'''मुफ्त हनीमून पैकेज के साथ भारतीय गंतव्य''',
        'index_ facility':'''यात्रा सुविधा''',
        'index_class':'''एस क्लास-एकोडोमेशन''',
        'index_dj ':'''संगीत और डीजे रात''',
        'index_after':'''शादी की शूटिंग के बाद''',
        'index_PHOTO':'''फोटोग्रैपी''',
        'index_DECORATORATION2':'''सजावट''',
        'index_guests1':'''100-150 मेहमान''',
        'index_PLATINUM':'''प्लैटिनम''',
        'index_withb':'''पेय पदार्थों के साथ भारतीय और महाद्वीपीय भोजन''',
        'index_honeyp':'''मुफ्त हनीमून पैकेज के साथ भारतीय और अंतर्राष्ट्रीय गंतव्य''',
        'index_facilitybus':'''एयरबस सुविधा''',
        'index_class':'''5 स्टार क्लास-एकोडोमेशन''',
        'index_djnight':'''संगीत, डीजे नाइट और लाइव कॉन्सर्ट''',
        'index_projection':'''प्रोजेक्टर डिस्प्ले के साथ शादी की शूटिंग के बाद''',
        'index_ photograpy':'''विचरण फोटोग्रैपी''',
        'index_ decorator':'''अंतर्राष्ट्रीय सजावट''',
        'index_GUESTS':'''100guests''',
        'index_Team2':'''टीम''',
        'index_your ':'''हमारी टीम के सदस्य आपकी खुशी डिजाइन करने के लिए''',
        'index_king':'''ज़ैक किंग''',
        'index_chief':'''मुख्य कार्यकारी अधिकारी''',
        'index_our':'''सपनों को क्राफ्ट करना, यादें बनाना: आपका गंतव्य, हमारी विशेषज्ञता। "''',
        'index_patel':'''द्रिशती पटेल''',
        'index_productmanager':'''उत्पाद प्रबंधक''',
        'index_unforgettable ':'''सपनों को अविस्मरणीय गंतव्यों में बदलना''',
        'index_lucy':'''ल्यूकिफायर किंग''',
        'index_CTO':'''सीटीओ''',
        'index_memories':'''"सपनों को क्राफ्ट करना, यादें बनाना: आपका परफेक्ट डेस्टिनेशन वेडिंग।"''',
        'index_Contact2':'''संपर्क''',
        'index_whene':'''जब भी आप चाहते हैं हमसे संपर्क करें''',
        'index_ouraddress':'''हमारा पता''',
        'index_address':'''A108 एडम स्ट्रीट, नई दिल्ली, 535022''',
        'index_emailus':'''हमें ईमेल करें''',
        'index_com':'''happywedding@gmail.com''',
        'index_callus':'''हमें बुलाओ''',
        'index_Copyright':'''कॉपीराइट''',
        'index_all':'''सर्वाधिकार सुरक्षित''',
        'index_by':'''द्वारा डिज़ाइन किया गया''',
        'index_hawed':'''क्यों एक खुश शादी?''',
        'index_decision':'''हमारे लिए, डेस्टिनेशन वेडिंग करने का निर्णय आसान था। यह यात्रा के लिए हमारे प्यार और हमारे करीबी दोस्तों और परिवार के साथ स्थायी यादें बनाने की हमारी इच्छा का प्रतिबिंब है। हम अपनी प्रतिज्ञाओं का आदान-प्रदान करने के लिए इससे अधिक सुंदर जगह की कल्पना नहीं कर सकते थे।''',
        'signup_cust':'''ग्राहक साइनअप''',
        'signup_first':'''पहला नाम:''',
        'signup_last':'''उपनाम:''',
        'signup_ema':'''ईमेल:''',
        'signup_uname':'''उपयोगकर्ता नाम''',
        'signup_pass':'''पासवर्ड''',
        'signup_cpass':'''पासवर्ड की पुष्टि कीजिये:''',
        'signup_up':'''साइन अप करें''',
        }
    if lang == 'es': return {
        'cancel_Bcancel':'''Tu reserva ha sido cancelada''',
        'cancel_cmail':'''El correo de cancelación se enviará pronto''',
        'cancel_done':'''HECHO''',
        'changepass_current':'''Contraseña actual:''',
        'changepass_new':'''Nueva contraseña:''',
        'confirm_Bconfirm':'''Tu reserva ha sido confirmada''',
        'confirm_conmail':'''El correo de confirmación se enviará pronto''',
        'confirm_condone':'''HECHO''',
        'index_happy':'''FELIZ BODA''',
        'index_HOME':'''Hogar''',
        'index_ABOUT':'''Acerca de''',
        'index_DEST':'''Destino''',
        'index_PRICE':'''Fijación de precios''',
        'index_SIGN':'''Inscribirse''',
        'index_HEY':'''Oye, soy vendedor''',
        'index_TEA':'''Equipo''',
        'index_LOG':'''Acceso''',
        'index_CONT':'''Contacto''',
        'index_WEL':'''Bienvenido''',
        'index_DESC':'''Somos un equipo de organizadores talentosos para hacer tus momentos''',
        'index_START':'''Empezar''',
        'index_Aboutsite':'''Nuestra feliz boda es un lugar para compartir la historia de amor de la pareja, su viaje para elegir una boda de destino y su entusiasmo por la próxima celebración. Proporciona un toque personal, que brinda a los invitados una idea de la relación de la pareja y las razones detrás de su elección de un destino para su día especial. También incluimos detalles sobre el significado del destino y lo que los invitados pueden esperar durante las festividades de la boda. En general, establece el tono para la experiencia de la boda e invita a los invitados a formar parte del viaje único de la pareja.''',
        'index_ques':'''Que esperar''',
        'index_detail':'''Prepárese para una celebración llena de amor, risas y momentos inolvidables. Desde ceremonias junto a la playa hasta explorar la cocina y la cultura locales, hemos planeado una experiencia inolvidable para nuestros invitados a la boda. Explore nuestro sitio web para encontrar detalles sobre arreglos de viaje, alojamientos y actividades durante nuestro fin de semana especial.''',
        'index_Destinations':'''Destinos''',
        'index_delhi':'''DELHI''',
        'index_delhidesc':'''La capital del país, es la capital para la boda étnica y hermosa.''',
        'index_rajasthan':'''Rajastán''',
        'index_rajdesc':'''La ciudad rosa de la India, hará que su boda sea colorida''',
        'index_kerala':'''Kerala''',
        'index_keraladesc':'''El propio país de Dios de la India, donde cae el cielo''',
        'index_swiz':'''SUIZA''',
        'index_swizdesc':'''Si tienes el deseo de tener una boda pura y de paz''',
        'index_luxe':'''Luxemburgo''',
        'index_luxedesc':'''El destino donde puedes tener momentos''',
        'index_paris':'''PARÍS''',
        'index_parisdesc':'''El destino para una boda rica y memorable''',
        'index_price1':'''Fijación de precios''',
        'index_price2':'''Fijación de precios''',
        'index_desired':'''Elija el paquete deseado''',
        'index_customise':'''Personalizar''',
        'index_customise1':'''personalizar''',
        'index_needs':'''Tus necesidades''',
        'index_addson':'''Con adds-on advnatage''',
        'index_Customise2':'''Personalizar''',
        'index_GOLD':'''ORO''',
        'index_cusine':'''COCINA INDIA''',
        'index_indian':'''Solo destino indio''',
        'index_MUSIC':'''MÚSICA''',
        'index_PHOTOGRAPY':'''Fotográfica''',
        'index_ACCODOMATIONS':'''Acodomaciones''',
        'index_DECORATORATION1':'''Decoración''',
        'index_guest':'''100 invitados''',
        'index_buynow':'''Comprar ahora''',
        'index_SILVER':'''PLATA''',
        'index_cont':'''Cocina india o continental''',
        'index_honey':'''Destino indio con paquete de luna de miel gratuito''',
        'index_ facility':'''Instalación de viaje''',
        'index_class':'''S Accodomaciones de clase S''',
        'index_dj ':'''Música y noche de DJ''',
        'index_after':'''Después del tiroteo en el matrimonio''',
        'index_PHOTO':'''Fotográfica''',
        'index_DECORATORATION2':'''Decoración''',
        'index_guests1':'''100-150 invitados''',
        'index_PLATINUM':'''PLATINO''',
        'index_withb':'''Cocina india y continental con bebidas''',
        'index_honeyp':'''Destino indio e internacional con paquete de luna de miel gratuito''',
        'index_facilitybus':'''Instalación de Airbus''',
        'index_class':'''Accodomaciones de 5 estrellas de clase''',
        'index_djnight':'''Música, Noche de DJ y concierto en vivo''',
        'index_projection':'''Después del tiroteo en el matrimonio con la pantalla del proyector''',
        'index_ photograpy':'''Fotograpía de destino''',
        'index_ decorator':'''Decoración internacional''',
        'index_GUESTS':'''100Gests''',
        'index_Team2':'''Equipo''',
        'index_your ':'''Miembros de nuestro equipo para diseñar su felicidad''',
        'index_king':'''Zack King''',
        'index_chief':'''Director ejecutivo''',
        'index_our':'''Elaboración de sueños, haciendo recuerdos: su destino, nuestra experiencia ".''',
        'index_patel':'''Drishti Patel''',
        'index_productmanager':'''Gerente de producto''',
        'index_unforgettable ':'''Convertir los sueños en destinos inolvidables''',
        'index_lucy':'''Rey lucifier''',
        'index_CTO':'''CTO''',
        'index_memories':'''"Elaborar sueños, crear recuerdos: tu boda de destino perfecta".''',
        'index_Contact2':'''Contacto''',
        'index_whene':'''Contáctenos cuando desee''',
        'index_ouraddress':'''Nuestra dirección''',
        'index_address':'''A108 Adam Street, Nueva Delhi, 535022''',
        'index_emailus':'''Envíanos un correo electrónico''',
        'index_com':'''happywedding@gmail.com''',
        'index_callus':'''Llámenos''',
        'index_Copyright':'''Derechos de autor''',
        'index_all':'''Reservados todos los derechos''',
        'index_by':'''Diseñada por''',
        'index_hawed':'''¿Por qué una BODA FELIZ?''',
        'index_decision':'''Para nosotros, la decisión de tener una boda de destino fue fácil. Es un reflejo de nuestro amor por los viajes y nuestro deseo de crear recuerdos duraderos con nuestros amigos y familiares más cercanos. No podríamos imaginar un lugar más hermoso para intercambiar nuestros votos.''',
        'signup_cust':'''Registro de clientes''',
        'signup_first':'''Nombre de pila:''',
        'signup_last':'''Apellido:''',
        'signup_ema':'''Correo electrónico:''',
        'signup_uname':'''Nombre de usuario''',
        'signup_pass':'''Contraseña''',
        'signup_cpass':'''Confirmar Contraseña:''',
        'signup_up':'''Inscribirse''',
        }
    if lang == 'ta': return {
        'cancel_Bcancel':'''உங்கள் முன்பதிவு ரத்து செய்யப்பட்டுள்ளது''',
        'cancel_cmail':'''ரத்து அஞ்சல் விரைவில் அனுப்பப்படும்''',
        'cancel_done':'''முடிந்தது''',
        'changepass_current':'''தற்போதைய கடவுச்சொல்:''',
        'changepass_new':'''புதிய கடவுச்சொல்:''',
        'confirm_Bconfirm':'''உங்கள் முன்பதிவு உறுதிப்படுத்தப்பட்டுள்ளது''',
        'confirm_conmail':'''உறுதிப்படுத்தல் அஞ்சல் விரைவில் அனுப்பப்படும்''',
        'confirm_condone':'''முடிந்தது''',
        'index_happy':'''திருமண வாழ்த்துக்கள்''',
        'index_HOME':'''வீடு''',
        'index_ABOUT':'''பற்றி''',
        'index_DEST':'''இலக்கு''',
        'index_PRICE':'''விலை''',
        'index_SIGN':'''பதிவுபெறுதல்''',
        'index_HEY':'''ஏய் நான் விற்பனையாளர்''',
        'index_TEA':'''அணி''',
        'index_LOG':'''உள்நுழைய''',
        'index_CONT':'''தொடர்பு''',
        'index_WEL':'''வரவேற்பு''',
        'index_DESC':'''உங்கள் தருணங்களை உருவாக்க நாங்கள் திறமையான அமைப்பாளர்களின் குழு''',
        'index_START':'''தொடங்கவும்''',
        'index_Aboutsite':'''எங்கள் மகிழ்ச்சியான திருமணமானது தம்பதியினரின் காதல் கதை, ஒரு இலக்கு திருமணத்தைத் தேர்ந்தெடுப்பதற்கான அவர்களின் பயணம் மற்றும் வரவிருக்கும் கொண்டாட்டத்தைப் பற்றிய அவர்களின் உற்சாகம் ஆகியவற்றைப் பகிர்ந்து கொள்வதற்கான இடம். இது ஒரு தனிப்பட்ட தொடர்பை வழங்குகிறது, விருந்தினர்களுக்கு தம்பதியரின் உறவு மற்றும் அவர்களின் சிறப்பு நாளுக்கு ஒரு இலக்கைத் தேர்ந்தெடுப்பதன் பின்னணியில் உள்ள காரணங்களை வழங்குகிறது. இலக்கின் முக்கியத்துவம் மற்றும் திருமண விழாக்களின் போது விருந்தினர்கள் என்ன எதிர்பார்க்கலாம் என்பது பற்றிய விவரங்களையும் நாங்கள் சேர்த்துக் கொள்கிறோம். ஒட்டுமொத்தமாக, இது திருமண அனுபவத்திற்கான தொனியை அமைக்கிறது மற்றும் விருந்தினர்களை தம்பதியரின் தனித்துவமான பயணத்தின் ஒரு பகுதியாக இருக்க அழைக்கிறது.''',
        'index_ques':'''என்ன எதிர்பார்க்க வேண்டும்''',
        'index_detail':'''காதல், சிரிப்பு மற்றும் மறக்க முடியாத தருணங்கள் நிறைந்த கொண்டாட்டத்திற்கு தயாராகுங்கள். பீச் சைட் விழாக்கள் முதல் உள்ளூர் உணவு மற்றும் கலாச்சாரத்தை ஆராய்வது வரை, எங்கள் திருமண விருந்தினர்களுக்கு மறக்க முடியாத அனுபவத்தை நாங்கள் திட்டமிட்டுள்ளோம். எங்கள் சிறப்பு வார இறுதியில் பயண ஏற்பாடுகள், தங்குமிடங்கள் மற்றும் செயல்பாடுகள் குறித்த விவரங்களைக் கண்டறிய எங்கள் வலைத்தளத்தை ஆராயுங்கள்.''',
        'index_Destinations':'''இடங்கள்''',
        'index_delhi':'''டெல்லி''',
        'index_delhidesc':'''நாட்டின் தலைநகரம், இன மற்றும் அழகான திருமணத்திற்கான தலைநகரம்''',
        'index_rajasthan':'''ராஜஸ்தான்''',
        'index_rajdesc':'''இந்தியாவின் பிங்க் சிட்டி, உங்கள் திருமணத்தை வண்ணமயமாக்கும்''',
        'index_kerala':'''கேரளா''',
        'index_keraladesc':'''இந்தியாவின் கடவுளின் சொந்த நாடு, அங்கு சொர்க்கம் விழுகிறது''',
        'index_swiz':'''சுவிட்சர்லாந்து''',
        'index_swizdesc':'''தூய்மையான மற்றும் சமாதான திருமணத்தை நீங்கள் விரும்பினால்''',
        'index_luxe':'''லக்சம்பர்க்''',
        'index_luxedesc':'''நீங்கள் தருணங்களை வைத்திருக்கக்கூடிய இலக்கு''',
        'index_paris':'''பாரிஸ்''',
        'index_parisdesc':'''பணக்கார மற்றும் மறக்கமுடியாத திருமணத்திற்கான இலக்கு''',
        'index_price1':'''விலை''',
        'index_price2':'''விலை''',
        'index_desired':'''விரும்பிய தொகுப்பைத் தேர்வுசெய்க''',
        'index_customise':'''தனிப்பயனாக்கலாம்''',
        'index_customise1':'''தனிப்பயனாக்கலாம்''',
        'index_needs':'''உங்கள் தேவைகள்''',
        'index_addson':'''சேர்க்கை-ஆன் அட்வொனாட்டேஜ் உடன்''',
        'index_Customise2':'''தனிப்பயனாக்கலாம்''',
        'index_GOLD':'''தங்கம்''',
        'index_cusine':'''இந்திய உணவு''',
        'index_indian':'''இந்திய இலக்கு மட்டுமே''',
        'index_MUSIC':'''இசை''',
        'index_PHOTOGRAPY':'''புகைப்பட சிகிச்சை''',
        'index_ACCODOMATIONS':'''அக்கறைகள்''',
        'index_DECORATORATION1':'''அலங்காரமானது''',
        'index_guest':'''100 விருந்தினர்கள்''',
        'index_buynow':'''இப்போது வாங்க''',
        'index_SILVER':'''வெள்ளி''',
        'index_cont':'''இந்திய அல்லது கண்ட உணவு''',
        'index_honey':'''இலவச தேனிலவு தொகுப்பு கொண்ட இந்திய இலக்கு''',
        'index_ facility':'''பயண வசதி''',
        'index_class':'''எஸ் வகுப்பு-கையகப்படுத்துதல்கள்''',
        'index_dj ':'''இசை மற்றும் டி.ஜே இரவு''',
        'index_after':'''திருமண படப்பிடிப்புக்குப் பிறகு''',
        'index_PHOTO':'''புகைப்பட சிகிச்சை''',
        'index_DECORATORATION2':'''அலங்காரமானது''',
        'index_guests1':'''100-150 விருந்தினர்கள்''',
        'index_PLATINUM':'''வன்பொன்''',
        'index_withb':'''பானங்களுடன் இந்திய மற்றும் கண்ட உணவு வகைகள்''',
        'index_honeyp':'''இலவச தேனிலவு தொகுப்புடன் இந்திய மற்றும் சர்வதேச இலக்கு''',
        'index_facilitybus':'''ஏர்பஸ் வசதி''',
        'index_class':'''5 நட்சத்திர வகுப்பு-கையகப்படுத்துதல்கள்''',
        'index_djnight':'''இசை, டி.ஜே இரவு மற்றும் நேரடி இசை நிகழ்ச்சி''',
        'index_projection':'''ப்ரொஜெக்டர் டிஸ்ப்ளேவுடன் திருமண படப்பிடிப்புக்குப் பிறகு''',
        'index_ photograpy':'''டெவன்சிஷன் ஃபோட்டோகிராபி''',
        'index_ decorator':'''சர்வதேச அலங்காரமானது''',
        'index_GUESTS':'''100GUESTS''',
        'index_Team2':'''அணி''',
        'index_your ':'''உங்கள் மகிழ்ச்சியை வடிவமைக்க எங்கள் குழு உறுப்பினர்கள்''',
        'index_king':'''சாக் கிங்''',
        'index_chief':'''தலைமை நிர்வாக அதிகாரி''',
        'index_our':'''கனவுகளை வடிவமைத்தல், நினைவுகளை உருவாக்குதல்: உங்கள் இலக்கு, எங்கள் நிபுணத்துவம். "''',
        'index_patel':'''த்ரிஷ்டி படேல்''',
        'index_productmanager':'''தயாரிப்பு மேலாளர்''',
        'index_unforgettable ':'''கனவுகளை மறக்க முடியாத இடங்களாக மாற்றுகிறது''',
        'index_lucy':'''லூசிஃபயர் கிங்''',
        'index_CTO':'''Cto''',
        'index_memories':'''"கனவுகளை வடிவமைத்தல், நினைவுகளை உருவாக்குதல்: உங்கள் சரியான இலக்கு திருமணம்."''',
        'index_Contact2':'''தொடர்பு''',
        'index_whene':'''நீங்கள் விரும்பும் போதெல்லாம் எங்களைத் தொடர்பு கொள்ளுங்கள்''',
        'index_ouraddress':'''எங்கள் முகவரி''',
        'index_address':'''A108 ஆடம் ஸ்ட்ரீட், புது தில்லி, 535022''',
        'index_emailus':'''எங்களுக்கு மின்னஞ்சல் அனுப்புங்கள்''',
        'index_com':'''happywedding@gmail.com''',
        'index_callus':'''எங்களை அழைக்கவும்''',
        'index_Copyright':'''பதிப்புரிமை''',
        'index_all':'''அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை''',
        'index_by':'''வடிவமைத்தவர்''',
        'index_hawed':'''மகிழ்ச்சியான திருமணம் ஏன்?''',
        'index_decision':'''எங்களைப் பொறுத்தவரை, ஒரு இலக்கு திருமணத்தை நடத்துவதற்கான முடிவு எளிதான ஒன்றாகும். இது பயணத்தின் மீதான எங்கள் அன்பின் பிரதிபலிப்பாகும், மேலும் எங்கள் நெருங்கிய நண்பர்கள் மற்றும் குடும்பத்தினருடன் நீடித்த நினைவுகளை உருவாக்குவதற்கான எங்கள் விருப்பம். எங்கள் சபதங்களை பரிமாறிக்கொள்ள இதைவிட அழகான இடத்தை எங்களால் கற்பனை செய்து பார்க்க முடியவில்லை.''',
        'signup_cust':'''வாடிக்கையாளர் பதிவுபெறுதல்''',
        'signup_first':'''முதல் பெயர்:''',
        'signup_last':'''கடைசி பெயர்:''',
        'signup_ema':'''மின்னஞ்சல்:''',
        'signup_uname':'''பயனர்பெயர்''',
        'signup_pass':'''கடவுச்சொல்''',
        'signup_cpass':'''கடவுச்சொல்லை உறுதிப்படுத்தவும்:''',
        'signup_up':'''பதிவு செய்க''',
        }
    if lang == 'ur': return {
        'cancel_Bcancel':'''آپ کی بکنگ منسوخ کردی گئی ہے''',
        'cancel_cmail':'''منسوخی میل جلد بھیج دیا جائے گا''',
        'cancel_done':'''کیا''',
        'changepass_current':'''موجودہ خفیہ لفظ:''',
        'changepass_new':'''نیا پاس ورڈ:''',
        'confirm_Bconfirm':'''آپ کی بکنگ کی تصدیق ہوگئی ہے''',
        'confirm_conmail':'''تصدیقی میل جلد بھیج دیا جائے گا''',
        'confirm_condone':'''کیا''',
        'index_happy':'''شادی مبارک''',
        'index_HOME':'''گھر''',
        'index_ABOUT':'''کے بارے میں''',
        'index_DEST':'''منزل''',
        'index_PRICE':'''قیمتوں کا تعین''',
        'index_SIGN':'''سائن اپ''',
        'index_HEY':'''ارے میں فروش ہوں''',
        'index_TEA':'''ٹیم''',
        'index_LOG':'''لاگ ان کریں''',
        'index_CONT':'''رابطہ کریں''',
        'index_WEL':'''خوش آمدید''',
        'index_DESC':'''ہم آپ کے لمحات بنانے کے لئے باصلاحیت منتظمین کی ٹیم ہیں''',
        'index_START':'''شروع کرنے کے''',
        'index_Aboutsite':'''ہماری ہیپی ویڈنگ جوڑے کی محبت کی کہانی ، منزل مقصود کی شادی کا انتخاب کرنے کے ان کا سفر ، اور آنے والے جشن کے بارے میں ان کے جوش و خروش کو بانٹنے کے لئے ایک جگہ ہے۔ یہ ایک ذاتی رابطے فراہم کرتا ہے ، جس سے مہمانوں کو جوڑے کے تعلقات اور ان کے خاص دن کے لئے منزل مقصود کے انتخاب کے پیچھے وجوہات کی بصیرت ملتی ہے۔ ہم منزل کی اہمیت کے بارے میں بھی تفصیلات شامل کرتے ہیں اور شادی کے تہواروں کے دوران مہمانوں کے منتظر کیا دیکھ سکتے ہیں۔ مجموعی طور پر ، یہ شادی کے تجربے کے ل the لہجے کا تعین کرتا ہے اور مہمانوں کو جوڑے کے انوکھے سفر کا حصہ بننے کی دعوت دیتا ہے۔''',
        'index_ques':'''کیا توقع کی جائے''',
        'index_detail':'''محبت ، ہنسی اور ناقابل فراموش لمحوں سے بھرا ہوا جشن کے لئے تیار ہوجائیں۔ ساحل سمندر کے کنارے تقاریب سے لے کر مقامی کھانوں اور ثقافت کی تلاش تک ، ہم نے اپنے شادی کے مہمانوں کے لئے ایک ناقابل فراموش تجربہ تیار کیا ہے۔ ہمارے خصوصی ویک اینڈ کے دوران سفری انتظامات ، رہائش اور سرگرمیوں کے بارے میں تفصیلات تلاش کرنے کے لئے ہماری ویب سائٹ کو دریافت کریں۔''',
        'index_Destinations':'''مقامات''',
        'index_delhi':'''دہلی''',
        'index_delhidesc':'''ملک کا دارالحکومت ، نسلی اور خوبصورت شادی کا دارالحکومت ہے''',
        'index_rajasthan':'''راجستھان''',
        'index_rajdesc':'''ہندوستان کا گلابی شہر ، آپ کی شادی کو رنگین بنائے گا''',
        'index_kerala':'''کیرالہ''',
        'index_keraladesc':'''خدا کا اپنا ملک ہندوستان ، جہاں آسمان گرتا ہے''',
        'index_swiz':'''سوئٹزرلینڈ''',
        'index_swizdesc':'''اگر آپ کے پاس خالص اور امن شادی کی خواہش ہے''',
        'index_luxe':'''لکسمبرگ''',
        'index_luxedesc':'''وہ منزل جہاں آپ لمحات ہوسکتے ہیں''',
        'index_paris':'''پیرس''',
        'index_parisdesc':'''امیر اور یادگار شادی کی منزل''',
        'index_price1':'''قیمتوں کا تعین''',
        'index_price2':'''قیمتوں کا تعین''',
        'index_desired':'''مطلوبہ پیکیج کا انتخاب کریں''',
        'index_customise':'''اپنی مرضی کے مطابق''',
        'index_customise1':'''اپنی مرضی کے مطابق''',
        'index_needs':'''آپ کی ضروریات''',
        'index_addson':'''ایڈس آن ایڈوانٹج کے ساتھ''',
        'index_Customise2':'''اپنی مرضی کے مطابق''',
        'index_GOLD':'''سونا''',
        'index_cusine':'''ہندوستانی کھانا''',
        'index_indian':'''صرف ہندوستانی منزل''',
        'index_MUSIC':'''موسیقی''',
        'index_PHOTOGRAPY':'''فوٹوگراپی''',
        'index_ACCODOMATIONS':'''تعی .ن''',
        'index_DECORATORATION1':'''ڈیکوریشن''',
        'index_guest':'''100 مہمان''',
        'index_buynow':'''ابھی خریدئے''',
        'index_SILVER':'''چاندی''',
        'index_cont':'''ہندوستانی یا براعظم کھانا''',
        'index_honey':'''مفت سہاگ رات کے پیکیج کے ساتھ ہندوستانی منزل''',
        'index_ facility':'''سفر کی سہولت''',
        'index_class':'''ایس کلاس-ایکواڈومیشنز''',
        'index_dj ':'''موسیقی اور ڈی جے نائٹ''',
        'index_after':'''شادی کی شوٹنگ کے بعد''',
        'index_PHOTO':'''فوٹوگراپی''',
        'index_DECORATORATION2':'''ڈیکوریشن''',
        'index_guests1':'''100-150 مہمان''',
        'index_PLATINUM':'''پلاٹینم''',
        'index_withb':'''مشروبات کے ساتھ ہندوستانی اور براعظم کھانا''',
        'index_honeyp':'''مفت ہنیمون پیکیج کے ساتھ ہندوستانی اور بین الاقوامی منزل''',
        'index_facilitybus':'''ایئربس سہولت''',
        'index_class':'''5 اسٹار کلاس-ایک کوڈ''',
        'index_djnight':'''موسیقی ، ڈی جے نائٹ اور براہ راست کنسرٹ''',
        'index_projection':'''پروجیکٹر ڈسپلے کے ساتھ شادی کی شوٹنگ کے بعد''',
        'index_ photograpy':'''تقدیر فوٹو گرافی''',
        'index_ decorator':'''بین الاقوامی سجاوٹ''',
        'index_GUESTS':'''100 گیسٹ''',
        'index_Team2':'''ٹیم''',
        'index_your ':'''ہماری ٹیم کے ممبران آپ کی خوشی کو ڈیزائن کریں''',
        'index_king':'''زیک کنگ''',
        'index_chief':'''چیف ایگزیکٹو آفیسر''',
        'index_our':'''خواب تیار کرنا ، یادیں بنانا: آپ کی منزل ، ہماری مہارت۔ "''',
        'index_patel':'''درشتی پٹیل''',
        'index_productmanager':'''پروڈکٹ مینیجر''',
        'index_unforgettable ':'''خوابوں کو ناقابل فراموش مقامات میں تبدیل کرنا''',
        'index_lucy':'''لوسیفائر کنگ''',
        'index_CTO':'''cto''',
        'index_memories':'''"خواب تیار کرنا ، یادیں پیدا کرنا: آپ کی کامل منزل کی شادی۔"''',
        'index_Contact2':'''رابطہ کریں''',
        'index_whene':'''جب چاہیں ہم سے رابطہ کریں''',
        'index_ouraddress':'''ہمارا پتہ''',
        'index_address':'''A108 ایڈم اسٹریٹ ، نئی دہلی ، 535022''',
        'index_emailus':'''ہمیں ای میل کریں''',
        'index_com':'''مبارک ہو wedding@gmail.com''',
        'index_callus':'''ہمیں بلائیں''',
        'index_Copyright':'''کاپی رائٹ''',
        'index_all':'''جملہ حقوق محفوظ ہیں''',
        'index_by':'''کی طرف سے ڈیزائن''',
        'index_hawed':'''شادی مبارک کیوں؟''',
        'index_decision':'''ہمارے لئے، منزل کی شادی کرنے کا فیصلہ ایک آسان تھا. یہ سفر کے لئے ہماری محبت اور ہمارے قریبی دوستوں اور کنبہ کے ساتھ دیرپا یادیں بنانے کی ہماری خواہش کی عکاسی کرتا ہے. ہم اپنی قسموں کا تبادلہ کرنے کے لئے اس سے زیادہ خوبصورت جگہ کا تصور بھی نہیں کرسکتے تھے۔''',
        'signup_cust':'''کسٹمر سائن اپ''',
        'signup_first':'''پہلا نام:''',
        'signup_last':'''آخری نام:''',
        'signup_ema':'''ای میل:''',
        'signup_uname':'''صارف نام''',
        'signup_pass':'''پاس ورڈ''',
        'signup_cpass':'''پاس ورڈ کی تصدیق کریں:''',
        'signup_up':'''سائن اپ''',
        }


def detectLanguage(request):
    languageDetected = supported_languages[0]
    pagePath = request.path
    if pagePath[-1] == '/': pagePath=pagePath[:-1]
    pagePath = pagePath.split('?')[0]
    pagePath = pagePath.split('#')[0]
    lastPath = pagePath.split('/')[-1]
    if lastPath in supported_languages[1:]:
        languageDetected = lastPath
    return languageDetected


def translated(requestOrLang,TranslateVariable):
    if requestOrLang in supported_languages:
        lang=requestOrLang
    else:
        lang = detectLanguage(requestOrLang)
    return translation_dictionary(lang)[TranslateVariable]


def localizeLink(request, link):
    lang=detectLanguage(request)
    if lang == supported_languages[0]: return link
    index1 = link.find('#')
    index2 = link.find('?')
    if index1 == -1 and index2 == -1: smallest_index = len(link)
    elif index1 == -1: smallest_index = index2
    elif index2 == -1: smallest_index = index1
    else: smallest_index = min(index1, index2)
    path = link[:smallest_index]
    if path[-1] == '/': path=path[:-1]
    return path+'/'+lang+link[smallest_index:]


from django.shortcuts import redirect as org_redirect
def redirect(request, to, *args, permanent=False, **kwargs):
    lang=detectLanguage(request)
    if lang in supported_languages[1:]:
        to=to+'_'+lang
    return org_redirect(to, *args, permanent=permanent, **kwargs)


from django.urls import path as org_path
def path(route, view, kwargs=None, name=None):
    if route == '':
        return [org_path('', view, kwargs, name),org_path('bn', view, kwargs, name+'_bn'),org_path('fr', view, kwargs, name+'_fr'),org_path('hi', view, kwargs, name+'_hi'),org_path('es', view, kwargs, name+'_es'),org_path('ta', view, kwargs, name+'_ta'),org_path('ur', view, kwargs, name+'_ur'),]
    if route[-1] == '/': route=route[:-1]
    return [org_path(route, view, kwargs, name),org_path(route+'/bn', view, kwargs, name+'_bn'),org_path(route+'/fr', view, kwargs, name+'_fr'),org_path(route+'/hi', view, kwargs, name+'_hi'),org_path(route+'/es', view, kwargs, name+'_es'),org_path(route+'/ta', view, kwargs, name+'_ta'),org_path(route+'/ur', view, kwargs, name+'_ur'),]


def langRef(path_ref):
    last=path_ref.split('/')[-1]
    if last in supported_languages:
        path_ref=path_ref[:-len(last)-1]
    result='<link rel="alternate" hreflang="en" href="'+addLinks(path_ref,'')+'" />\n'
    result+='<link rel="alternate" hreflang="bn" href="'+addLinks(path_ref,'bn')+'" />\n'
    result+='<link rel="alternate" hreflang="fr" href="'+addLinks(path_ref,'fr')+'" />\n'
    result+='<link rel="alternate" hreflang="hi" href="'+addLinks(path_ref,'hi')+'" />\n'
    result+='<link rel="alternate" hreflang="es" href="'+addLinks(path_ref,'es')+'" />\n'
    result+='<link rel="alternate" hreflang="ta" href="'+addLinks(path_ref,'ta')+'" />\n'
    result+='<link rel="alternate" hreflang="ur" href="'+addLinks(path_ref,'ur')+'" />\n'
    result+='<link rel="alternate" hreflang="x-default" href="'+addLinks(path_ref,'')+'" />\n'
    return result


from django.urls import get_resolver
def translatedLinks(lang):
    names=[]
    for i in get_resolver().url_patterns:
        if hasattr(i, 'name'):
            if i.name:
                names.append(i.name)
    result = {}
    if lang == supported_languages[0]:
        for i in names:
            if i[-3:] not in ['_bn', '_fr', '_hi', '_es', '_ta', '_ur'] and names.count(i+'_bn'):
                result.update({i:i})
        return result
    for i in names:
        if names.count(i+'_'+lang):
            result.update({i:i+'_'+lang})
    return result


def languageMenu(request, lang):
    path = request.path
    remainder = request.get_full_path()[len(path):]
    selected = [' ', ' ', ' ', ' ', ' ', ' ', ' ']
    selected[supported_languages.index(lang)]=' selected '
    if supported_languages.index(lang):
        path=path[:-3]
    result = '<select id="languageMenu" onchange="window.location = this.value;">'
    if path == '/': path = ''
    if path =='':
        result += '<option'+selected[0]+'value="/'+remainder+'">English (English)</option>'
    else:
        result += '<option'+selected[0]+'value="' + path + remainder +'">English (English)</option>'
    result += '<option'+selected[1]+'value="' + path +'/bn'+remainder+'">Bengali (বাংলা)</option>'
    result += '<option'+selected[2]+'value="' + path +'/fr'+remainder+'">French (Français)</option>'
    result += '<option'+selected[3]+'value="' + path +'/hi'+remainder+'">Hindi (हिन्दी)</option>'
    result += '<option'+selected[4]+'value="' + path +'/es'+remainder+'">Spanish (Español)</option>'
    result += '<option'+selected[5]+'value="' + path +'/ta'+remainder+'">Tamil (தமிழ்)</option>'
    result += '<option'+selected[6]+'value="' + path +'/ur'+remainder+'">Urdu (اردو)</option>'
    result += '</select>'
    return result


from django.shortcuts import render as org_render
def render(request, template_name, context=None, *args, **kwargs):
    lang=detectLanguage(request)
    if context == None:
        context={}
    return org_render(request, template_name, {**context,
                                                **translation_dictionary(lang),
                                                'lang':lang,
                                                'languageReferences':langRef(request.build_absolute_uri()),
                                                'languageMenu':languageMenu(request, lang),
                                                'candyLink':translatedLinks(lang),
                                                }, *args, **kwargs)


def addLinks(*args):
    result=''
    for i in args:
        if result and result[-1]=='/':result=result[:-1]
        if i and i[-1]=='/':i=i[:-1]
        if i and i[0]=='/':i=i[1:]
        if result and i: result+='/'
        result+=i
    return result


def provideSitemap(request, add_pages=[], remove_pages=[], remove_paths=[]):
    from django.http import HttpResponse
    result='<?xml version="1.0" encoding="UTF-8"?>'+'\n'
    result+='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+'\n'
    domain= request.build_absolute_uri()
    domain=domain.split('/')[0]+'//'+domain.split('/')[2]+'/'
    paths = []
    for i in get_resolver().url_patterns:
        if str(type(i))=="<class 'django.urls.resolvers.URLPattern'>":
            try:
                route=i.pattern._route
                route=route.split('<')[0]
                if not route == 'sitemap.xml':
                    if 'robots.txt' not in route:
                        paths.append(addLinks(domain,route))
            except: pass
    paths+=add_pages
    paths=list(dict.fromkeys(paths))
    for route in paths:
        removed_path = False
        for removal in remove_paths:
            if route[:len(removal)] == removal: removed_path = True
        if not removed_path and route not in remove_pages:
            result+='<url>'+'\n'
            result+='<loc>'+route+'</loc>'+'\n'
            result+='</url>'+'\n'
    result+='</urlset>'
    result= result.encode('utf-8')
    return HttpResponse(result, content_type='application/xml; charset=utf-8')


def sitemap(add_pages=[], remove_pages=[], remove_paths=[]):
    return [org_path('sitemap.xml', provideSitemap,{'add_pages' :add_pages,'remove_pages': remove_pages, 'remove_paths': remove_paths})]


